name: Docker Build latest package (from main)

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    workflow_dispatch:

jobs:
    build_staging:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: get-npm-version
                id: package-version
                uses: martinbeentjes/npm-get-version-action@main
            -   name: docker login
                env:
                    DOCKER_USER: ${{ secrets.DOCKER_USER }}
                    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                run: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            -   name: docker build
                run: |
                    docker build --build-arg ANGULAR_ENV=staging -t farscrl/chalender-frontend:latest-staging .
            -   name: docker push
                run: |
                    docker push farscrl/chalender-frontend --all-tags

    build_prod:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: get-npm-version
                id: package-version
                uses: martinbeentjes/npm-get-version-action@main
            -   name: docker login
                env:
                    DOCKER_USER: ${{ secrets.DOCKER_USER }}
                    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                run: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            -   name: docker build
                run: |
                    docker build --build-arg ANGULAR_ENV=prod -t farscrl/chalender-frontend:latest-prod .
            -   name: docker push
                run: |
                    docker push farscrl/chalender-frontend --all-tags
